# Generated by Django 5.2.8 on 2025-11-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
