# Generated by Django 5.2.8 on 2025-11-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('CVV', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
