# Generated by Django 5.2.8 on 2025-11-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='CVV',
            field=models.IntegerField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(max_length=16, unique=True),
        ),
    ]
