# Generated by Django 5.2.8 on 2025-11-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_card_cvv_alter_card_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='CVV',
            new_name='cvv',
        ),
    ]
