# Generated by Django 5.2.8 on 2025-12-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_card_card_number_alter_card_cvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField(max_length=18)),
            ],
        ),
    ]
