# Generated by Django 5.2.8 on 2025-12-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_user_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
