# Generated by Django 5.2.8 on 2025-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('unique_pass', models.CharField(max_length=20, unique=True)),
                ('login_name', models.CharField(max_length=30)),
            ],
        ),
    ]
